{{- if .Values.ingressTest.enabled -}}
{{- $fullName := include "+( .AppName ).fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- $firstPorts := dict }}
{{- if $.Values.service.ports }}
{{- $firstPorts = mustFirst $.Values.service.ports }}
{{- end }}
{{- $defPort := coalesce $.Values.service.port $firstPorts.port }}
{{- $port := coalesce $.Values.service.port $firstPorts.port $defPort }}

{{- $globalRewrite := index $.Values.ingress.annotations "konghq.com/rewrite" | default "" -}}
{{- /* Omit the global konghq.com/rewrite to avoid duplication below */ -}}
{{- $globalAnnots := omit $.Values.ingress.annotations "konghq.com/rewrite" -}}

{{- range $hostIdx, $hostEntry := .Values.ingress.hosts }}
  {{- range $pathIdx, $path := $hostEntry.paths }}
    {{- $trimmedPath := trimSuffix "/" $path.path }}
    {{- $pathSuffix := regexFind "[^/]+$" $trimmedPath }}
    {{- $rewritePath := coalesce $path.rewrite $globalRewrite }}

---
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $pathSuffix }}
  labels:
    {{- include "+( .AppName ).labels" $ | nindent 4 }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml $globalAnnots | nindent 4 }}
    {{- if $rewritePath }}
    konghq.com/rewrite: "{{ $rewritePath }}"
    {{- end }}
  {{- end }}
spec:
  {{- if and $.Values.ingress.className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  {{- if $.Values.ingress.tls }}
  tls:
    {{- range $.Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $hostEntry.host | quote }}
      http:
        paths:
          - path: {{ $path.path }}
            {{- if and $path.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $path.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $port }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $port }}
              {{- end }}
  {{- end }}
{{- end }}
{{- end }}

